### ISSUE TITLE
AttributeError: 'HarParser' object has no attribute 'entries'

### ISSUE THREAD

**Issue by nserebry** [mrname/haralyzer#18]
Running into the issue:
My .har file contains :  `"pages": [],` and  seems like no way to parse the entries: 

```
 "pages": [],
    "entries": [
      {
    .... 
    }

```

So below code will fail: 

```
har_p = HarParser(json.loads((open(self.har_f_path).read())))   
print(har_p.entries)
AttributeError: 'HarParser' object has no attribute 'entries'
```

**Comment by mrname** [comment]
Hello @nserebry thanks for using Haralyzer!

The issue here is that `entries` are an attribute of the `HarPage` object, not the `HarParser` itself. The concept here is that a HAR file can have one or more pages. So, the parser stores information about the full run captured by the HAR file, whereas the `HarPage` objects have all of the details about that particular page. This is illustrated in the example here:

https://github.com/mrname/haralyzer#advanced-usage

Let me know if that solves the issue for you. Also, the fact that this stumped you would indicate that the docs are not good enough. Feel free to open a PR for docs updates or I can do it if you have suggestions on how to make things clearer.

**Comment by mrname** [comment]
@nserebry did that clear things up for you?

**Comment by mrname** [comment]
@nserebry I'm going to go ahead and close this out. Please update this thread if you have any suggestions on how to improve the documentation, or if you have further issues with this feature, thanks!
